const projects = [
  {
    id: 1,
    title: "Reservia",
    image: "reservia.png",
    images: [
      "reservia.png",
      "reservia_2.PNG",
      "reservia_3.PNG",
      "reservia_4.PNG",
    ],
    description: "Transformer une maquette en site web avec HTML & CSS",
    link: "https://floriansaliba.github.io/FlorianSaliba_2_04062021/",
    github: "https://github.com/Floriansaliba/FlorianSaliba_2_04062021",
    technologies: ["HTML", "CSS"],
    about:
      "Reservia est le projet 2 de ma formation OpenClassrooms. Le but étant de développer une landing page responsive de site de réservation de logement en ligne, à partir d'une maquette. Ce projet a été développé en HTML et CSS",
  },
  {
    id: 2,
    title: "Ohmyfood",
    image: "ohmyfood.PNG",
    images: ["ohmyfood_2.png", "ohmyfood_3.png", "ohmyfood_4.png"],
    description: "Dynamiser une page web avec des animations CSS",
    link: "https://floriansaliba.github.io/ohmyfood/",
    github: "https://github.com/Floriansaliba/ohmyfood",
    technologies: ["HTML", "CSS", "REACT.JS", "SCSS", "REDUX"],
    about: `OhMyFood est une application permettant de reserver des restaurants ainsi que le menu désiré. Le site a été codé dans le cadre du projet 3 de ma formation OpenClassrooms, et privilégie une approche mobile first. Le CSS a été généré grâce au prépocesseur Sass. Le but était de maîtriser les animations CSS modernes notemment par l'utilisation des keyframes.`,
  },
  {
    id: 3,
    title: "GameOn",
    image: "gameon.PNG",
    images: ["gameon.PNG", "gameon_2.PNG", "gameon_3.PNG"],
    description: "Créer une landing page avec Javascript",
    link: "https://floriansaliba.github.io/GameOn-website-FR/#",
    github: "https://github.com/Floriansaliba/GameOn-website-FR/tree/main",
    technologies: ["JAVASCRIPT", "HTML", "CSS"],
    about: `GameOn est le projet 4 de mon parcours OpenClassrooms. Ce dernier représente une landing page d'un site d'évenementiel dédié aux tournois de jeux vidéo. Le but de l'exercice était d'utiliser Javascript afin d'animer l'aparition d'une modal, et valider le formulaire côté front. Un message de confirmation s'affiche afin de notifier l'utilisateur que son inscription a bien été prise en compte.`,
  },
  {
    id: 4,
    title: "Fisheye",
    image: "FishEye.PNG",
    images: ["fishEye_2.PNG", "fishEye_3.PNG", "fishEye_4.PNG"],
    description: "Créer un site accessible pour une plateforme de photographes",
    link: "",
    github: "https://github.com/Floriansaliba/FishEye",
    technologies: ["HTML", "CSS", "JAVASCRIPT"],
    about: `FishEye est une plateforme de photographes. Ces derniers pourrons afficher leur profil ainsi que leurs photos / vidéos. 
      Les profils ont été récupérés au format JSON, et disposés selon la maquette Figma. Les pages respectent les contraintes d'accessibilité (WAI). L'utilisateur pourra faire défiler les images d'un photographe grâce à un slider. `,
  },
  {
    id: 5,
    title: "Les petits plats",
    image: "les_petits_plats.PNG",
    images: [
      "les_petits_plats.PNG",
      "les_petits_plats_2.PNG",
      "les_petits_plats_3.PNG",
    ],
    description: "Développez un algorithme de recherche en JavaScript",
    link: "https://floriansaliba.github.io/les_petits_plats/",
    github: "https://github.com/Floriansaliba/les_petits_plats",
    technologies: ["HTML", "SCSS", "JAVASCRIPT"],
    about: `L'application Les Petits Plats, projet 7 de ma formation OpenClassrooms, permet gâce à un algorithme de recherche codé en Javascript, de pouvoir trouver son plat préféré parmis une centaine de listes de recettes. Les recettes sont filtrées en fonction de ce que l'utilisateur tape dans la barre de recherche. Les tags (ustensiles de cuisine, ingrédients ou appareils de cuisine) permettrons d'affiner la recherche. `,
  },
  {
    id: 6,
    title: "Billed",
    image: "billed.PNG",
    images: ["billed_2.PNG", "billed_3.PNG", "billed_4.PNG"],
    description: "Débugger et tester un SaaS RH",
    link: "",
    github: "https://github.com/Floriansaliba/billed-app",
    technologies: ["JAVASCRIPT", "HTML", "CSS", "JEST"],
    about: `Billed est le projet 9 de mon parcours Openclassrooms. 
      Comme son nom l'indique, cette application permet la soumission de notes de frais par les employés, et une validation de ces dernières par les administrateurs RH.  Mon rôle était de débugger l'application, ainsi que de vérifier son bon fonctionnement grâce aux tests unitaires et tests d'intégration, et ainsi obtenir une couverture totale des test à plus de 90%. `,
  },
  {
    id: 7,
    title: "Learn@Home",
    image: "learn@home.png",
    images: ["learn@home_2.png", "learn@home_3.png", "learn@home_4.png"],
    description: "Définir les besoins pour une app de soutien scolaire",
    link: "https://www.figma.com/file/lFAqwEBTZPc8lflTccCZa0/Maquette-Learn%40Home?node-id=0%3A1",
    github: "",
    technologies: ["FIGMA"],
    about: `Learn@Home est le projet 10 de mon parcours Openclassrooms. Ce projet consiste à proposer une maquette de site permettant à des étudiants et des tuteurs de converser, s'ajouter des tâches et gérer leurs calendrier afin de positionner des séances de mentorat. Il m'a fallu mettre en place les user stories et créer une maquette via l'outil Figma. `,
  },
  {
    id: 8,
    title: "Kasa",
    image: "kasa.PNG",
    images: ["kasa.PNG", "kasa_2.PNG", "kasa_3.PNG"],
    description: "Développer une application Web avec React et React Routeur",
    link: "",
    github: "https://github.com/Floriansaliba/Kasa",
    technologies: ["REACT.JS", "JAVASCRIPT", "HTML", "CSS"],
    about: `Projet 11 de mon parcours Openclassrooms, Kasa est une application développée en React.js permettant de parcourirs les appartements parisiens disponibles à la location.  `,
  },
  {
    id: 9,
    title: "SportSee",
    image: "sportsee.PNG",
    images: ["sportsee.PNG"],
    description: "Développer un tableau de bord d'analytics avec React",
    link: "",
    github: "https://github.com/Floriansaliba/sportsee",
    technologies: ["REACT.JS", "RECHARTS"],
    about: `SportSee est une application développée dans le cadre du projet 12 de mon parcours OpenClassrooms. Elle permet d'afficher les statistiques sportives de ses utilisateurs sous forme de graphique. J'ai développé cette application en React.js, notemment avec la librairie Raichart pour l'affichage des données graphiques.`,
  },
  {
    id: 10,
    title: "Argent bank",
    image: "argentbank.PNG",
    images: ["argentbank.PNG", "argentbank_2.PNG"],
    description:
      "Utiliser une API pour un compte utilisateur bancaire avec React",
    link: "",
    github: "https://github.com/Floriansaliba/argent_bank",
    technologies: ["REACT.JS", "REDUX"],
    about: `Argent Bank est une application bancaire permettant au utilisateurs d'avoir acces à leurs comptes et modifier leurs profils. Les données utilisateurs ont été récupérées via des appels API. J'ai utilisé Redux pour gérer l'état de mes composants de manière globale. `,
  },
  {
    id: 11,
    title: "HRnet",
    image: "hrnet.PNG",
    images: ["hrnet_2.png", "hrnet_3.png"],
    description: "Faire passer une librairie jQuery vers React",
    link: "",
    github: "https://github.com/Floriansaliba/Wealth_Health",
    technologies: ["REACT.JS"],
    about: `HRNet est une application RH permettant d'enregistrer les nouveaux employés, et d'avoir accès à la liste des employés créés. Dernier projet de ma formation OpenClassrooms, le but était de convertir l'ancienne version développée en Jquery, en nouvelle application React.js. `,
  },
];

export default projects;
